spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:efgen_bosh}?currentSchema=${DB_SCHEMA:work}
    username: ${DB_USER:efgen_bosh}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:work}

logging:
  level:
    org.springframework.web: debug
    org.hibernate.SQL: debug
